[upstreams]
    [upstream]
        upstream = "up_image"
        [host]
        ip = "192.168.115.69"
        port = 20101
        weight = 10

        [host]
        ip = "192.168.115.100"
        port = 20101
        weight = 10

    [upstream]
        upstream = "zhaopin"
        [host]
        ip = "192.168.115.69"
        port = 20101
        weight = 10

        [host]
        ip = "192.168.115.100"
        port = 20101
        weight = 10

[hosts]
    [host]
        host = "www.ganji.com"
        [locations]
            [location]
            location = "/tel_img"
            upstream = "up_image"
            [location]
            location = "/wap"
            upstream = "wap"
            [location]
            location = "/m"
            upstream = "wap"
            [location]
            location = "/3g"
            upstream = "wap"
            [location]
            location = "/fang*"
            upstream = "fang"
            [location]
            location = "/zp*"
            upstream = "zhaopin"
            [location]
            location = "/jz*"
            upstream = "zhaopin"
            [location]
            location = "/qz*"
            upstream = "zhaopin"
            [location]
            location = "/qjz*"
            upstream = "zhaopin"
            [location]
            location = "/zhaopin*"
            upstream = "zhaopin"
            [locaiont]
            location = "/wanted*"
            upstream = "zhaopin"
    [host]
        host = "*.ganji.cn"
        [locations]
            [location]
            location = "/*"
            upstream = "wap"

